from __future__ import annotations

from pathlib import Path
import os
import tempfile
import time
import uuid

from .actions import Action, noop
from .config import AppConfig
from .inst import read_inst_xml
from .parser import parse_observation_xml
from .models import Observation
from .window_controller import close_window, dismiss_window_with_enter


class ScenarioEnded(RuntimeError):
    """CMO 시나리오가 정상적으로 종료됨."""

    def __init__(
        self,
        message: str,
        final_observation: Observation | None = None,
        success_hint: bool = False,
    ):
        super().__init__(message)
        self.final_observation = final_observation
        self.success_hint = success_hint


class FileProtocol:
    def __init__(self, config: AppConfig):
        self.config = config
        self._last_signature: tuple[int, int] | None = None
        self._action_sequence = 0
        self._action_session = uuid.uuid4().hex
        self._special_message_seen_at: float | None = None

    def _recent_special_message(self) -> bool:
        return bool(
            self._special_message_seen_at is not None
            and time.monotonic() - self._special_message_seen_at <= 10.0
        )

    def has_recent_success_hint(self) -> bool:
        """Whether a Special Messages dialog immediately preceded completion."""
        return self._recent_special_message()

    def send(self, action: Action) -> str:
        path = self.config.action_path
        path.parent.mkdir(parents=True, exist_ok=True)

        self._action_sequence += 1
        sequence = self._action_sequence
        action_id = f"{self._action_session}:{sequence}"

        content = (
            "-- Generated by pycmo_tutorial3 Python client.\n"
            f"local action_id = '{action_id}'\n"
            "if action_id ~= PYCMO_LAST_ACTION_ID then\n"
            "    -- Mark before execution so an action that raises is not retried forever.\n"
            "    PYCMO_LAST_ACTION_ID = action_id\n"
            "    PYCMO_LAST_ACTION_RESULT_ID = action_id\n"
            "    PYCMO_LAST_ATTACK_ASSIGNED = nil\n"
            "    PYCMO_LAST_ASSIGNED_WEAPON_DBID = nil\n"
            "    local ok, err = pcall(function()\n"
            f"{action.lua}\n"
            "    end)\n"
            "    if not ok then\n"
            "        print('PyCMO action error: ' .. tostring(err))\n"
            "    end\n"
            "end\n"
        )

        max_attempts = 100
        retry_interval = 0.1

        last_error: PermissionError | None = None

        for attempt in range(1, max_attempts + 1):
            temporary: str | None = None

            try:
                fd, temporary = tempfile.mkstemp(
                    prefix=path.stem + "_",
                    suffix=".tmp",
                    dir=path.parent,
                    text=True,
                )

                with os.fdopen(
                    fd,
                    "w",
                    encoding="utf-8",
                    newline="\n",
                ) as handle:
                    handle.write(content)
                    handle.flush()
                    os.fsync(handle.fileno())

                # CMO가 기존 action 파일을 읽는 순간에는
                # Windows가 os.replace()를 거부할 수 있다.
                os.replace(temporary, path)

                return action_id

            except PermissionError as exc:
                last_error = exc

                if temporary is not None:
                    try:
                        Path(temporary).unlink(missing_ok=True)
                    except OSError:
                        pass

                if attempt % 10 == 0:
                    print(
                        "CMO가 action 파일을 사용 중입니다. "
                        f"재시도 {attempt}/{max_attempts}"
                    )

                time.sleep(retry_interval)

            except Exception:
                if temporary is not None:
                    try:
                        Path(temporary).unlink(missing_ok=True)
                    except OSError:
                        pass

                raise

        raise PermissionError(
            "CMO가 action 파일을 계속 사용 중이어서 "
            f"{max_attempts * retry_interval:.1f}초 동안 "
            f"교체하지 못했습니다: {path}"
        ) from last_error

    def initialize_action_file(self) -> None:
        self.send(noop())

    def prepare_for_scenario_restart(self) -> None:
        """
        이전 시나리오의 관측 파일은 stale 상태로 표시하고,
        이전 종료 마커는 제거한다.
        """
        self._special_message_seen_at = None
        observation_path = self.config.observation_path

        if observation_path.exists():
            try:
                stat = observation_path.stat()
                self._last_signature = (
                    stat.st_mtime_ns,
                    stat.st_size,
                )
            except OSError:
                self._last_signature = None
        else:
            self._last_signature = None

        ended_path = self.config.scenario_ended_path

        try:
            ended_path.unlink(missing_ok=True)
        except OSError as exc:
            raise RuntimeError(
                "이전 scenario-ended 파일을 제거하지 못했습니다: "
                f"{ended_path}"
            ) from exc

    def clear_scenario_ended_marker(self) -> None:
        """이전 시나리오의 종료 마커만 제거한다."""
        path = self.config.scenario_ended_path

        try:
            path.unlink(missing_ok=True)
        except OSError as exc:
            raise RuntimeError(
                "이전 scenario-ended 파일을 제거하지 못했습니다: "
                f"{path}"
            ) from exc

    def _ended(self) -> bool:
        """
        CMO가 생성한 scenario-ended 파일에서 종료 상태를 읽는다.

        파일이 단순히 'true'이거나,
        XML/INST 내부에 '<Comment>true</Comment>'가 있는 경우를
        모두 처리한다.
        """
        path = self.config.scenario_ended_path

        if not path.exists():
            return False

        try:
            text = path.read_text(
                encoding="utf-8",
                errors="replace",
            )
        except OSError:
            return False

        normalized = text.strip().lower()

        if normalized == "true":
            return True

        # CMO .inst 파일 내부에 true가 기록되는 경우
        return (
            "<comment>true</comment>" in normalized
            or ">true<" in normalized
        )

    def _get_observation_signature(
        self,
    ) -> tuple[int, int] | None:
        """
        관측 파일의 변경 여부를 판단하기 위한
        (수정 시간, 파일 크기) 서명을 반환한다.
        """
        path = self.config.observation_path

        try:
            if not path.exists():
                return None

            stat = path.stat()

            if stat.st_size <= 0:
                return None

            return (
                stat.st_mtime_ns,
                stat.st_size,
            )
        except OSError:
            return None

    def _try_read_current(self) -> Observation | None:
        """
        관측 파일이 쓰이는 중이면 None을 반환한다.
        정상적으로 읽으면 Observation을 반환한다.
        """
        try:
            return self.read_current()
        except (OSError, ValueError):
            return None

    def read_current(self) -> Observation:
        xml = read_inst_xml(
            self.config.observation_path
        )

        return parse_observation_xml(
            xml,
            scenario_ended=self._ended(),
        )

    def wait_for_new(
        self,
        allow_existing_first: bool = True,
        timeout_seconds: float | None = None,
    ) -> Observation:
        """
        새 관측 파일 또는 시나리오 종료 마커를 기다린다.

        새 관측이 도착하면 Observation을 반환한다.

        시나리오가 종료되면 ScenarioEnded를 발생시킨다.
        종료 직전에 최종 관측 파일이 갱신되었다면
        ScenarioEnded.final_observation에 담아 전달한다.
        """
        observation_path = self.config.observation_path

        if timeout_seconds is None:
            timeout_seconds = (
                self.config.protocol.observation_timeout_seconds
            )
        poll_interval = (
            self.config.protocol.poll_interval_seconds
        )

        deadline = time.monotonic() + timeout_seconds

        while time.monotonic() < deadline:
            if (
                self.config.auto_reset.dismiss_special_messages_dialog
                and close_window(
                    self.config.auto_reset.special_messages_window_title
                )
            ):
                self._special_message_seen_at = time.monotonic()
                print("[CMO dialog] Special Messages window closed.")
                time.sleep(poll_interval)
                continue

            if (
                self.config.auto_reset.dismiss_scenario_end_dialog
                and dismiss_window_with_enter(
                    self.config.auto_reset.scenario_end_window_title
                )
            ):
                final_observation = self._try_read_current()
                raise ScenarioEnded(
                    "CMO Scenario End 창을 닫고 에피소드를 종료했습니다.",
                    final_observation=final_observation,
                    success_hint=self._recent_special_message(),
                )

            signature = self._get_observation_signature()

            is_new_observation = (
                signature is not None
                and (
                    signature != self._last_signature
                    or (
                        allow_existing_first
                        and self._last_signature is None
                    )
                )
            )

            # 종료 마커가 존재하는 경우:
            # 종료 직전에 최종 observation이 갱신됐는지 먼저 확인한다.
            if self._ended():
                final_observation: Observation | None = None

                if is_new_observation:
                    final_observation = self._try_read_current()

                    if final_observation is not None:
                        self._last_signature = signature

                raise ScenarioEnded(
                    "CMO 시나리오가 정상적으로 종료되었습니다.",
                    final_observation=final_observation,
                    success_hint=self._recent_special_message(),
                )

            # 종료가 아니고 새 관측이 있으면 정상 반환한다.
            if is_new_observation:
                observation = self._try_read_current()

                if observation is not None:
                    self._last_signature = signature
                    return observation

            time.sleep(poll_interval)

        # 반복문 종료 직전에 종료 마커가 생성됐을 수 있으므로
        # 한 번 더 검사한다.
        if self._ended():
            final_observation: Observation | None = None
            signature = self._get_observation_signature()

            if (
                signature is not None
                and signature != self._last_signature
            ):
                final_observation = self._try_read_current()

                if final_observation is not None:
                    self._last_signature = signature

            raise ScenarioEnded(
                "CMO 시나리오가 정상적으로 종료되었습니다.",
                final_observation=final_observation,
                success_hint=self._recent_special_message(),
            )

        raise TimeoutError(
            f"새 관측 파일을 기다리다 시간 초과: "
            f"{observation_path}\n"
            "CMO에서 bootstrap.lua가 실행되었는지, "
            "scenario.title이 정확한지 확인하십시오. "
            "auto_reset이 최근 저장본을 불러왔다면 그 저장본에도 "
            "PyCMO 이벤트가 포함되어 있어야 합니다."
        )
