from __future__ import annotations

from pathlib import Path
import os
import tempfile
import time

from .actions import Action, noop
from .config import AppConfig
from .inst import read_inst_xml
from .parser import parse_observation_xml
from .models import Observation


class FileProtocol:
    def __init__(self, config: AppConfig):
        self.config = config
        self._last_signature: tuple[int, int] | None = None

    def send(self, action: Action) -> None:
        path = self.config.action_path
        path.parent.mkdir(parents=True, exist_ok=True)

        content = (
            "-- Generated by pycmo_tutorial3 Python client.\n"
            "local ok, err = pcall(function()\n"
            f"{action.lua}\n"
            "end)\n"
            "if not ok then\n"
            "    print('PyCMO action error: ' .. tostring(err))\n"
            "end\n"
        )

        max_attempts = 100
        retry_interval = 0.1

        last_error: PermissionError | None = None

        for attempt in range(1, max_attempts + 1):
            temporary: str | None = None

            try:
                fd, temporary = tempfile.mkstemp(
                    prefix=path.stem + "_",
                    suffix=".tmp",
                    dir=path.parent,
                    text=True,
                )

                with os.fdopen(
                    fd,
                    "w",
                    encoding="utf-8",
                    newline="\n",
                ) as handle:
                    handle.write(content)
                    handle.flush()
                    os.fsync(handle.fileno())

                # CMO가 기존 action 파일을 읽는 순간에는
                # Windows가 os.replace()를 거부할 수 있다.
                os.replace(temporary, path)

                return

            except PermissionError as exc:
                last_error = exc

                if temporary is not None:
                    try:
                        Path(temporary).unlink(missing_ok=True)
                    except OSError:
                        pass

                if attempt % 10 == 0:
                    print(
                        "CMO가 action 파일을 사용 중입니다. "
                        f"재시도 {attempt}/{max_attempts}"
                    )

                time.sleep(retry_interval)

            except Exception:
                if temporary is not None:
                    try:
                        Path(temporary).unlink(missing_ok=True)
                    except OSError:
                        pass

                raise

        raise PermissionError(
            "CMO가 action 파일을 계속 사용 중이어서 "
            f"{max_attempts * retry_interval:.1f}초 동안 교체하지 못했습니다: "
            f"{path}"
        ) from last_error

    def initialize_action_file(self) -> None:
        self.send(noop())

    def prepare_for_scenario_restart(self) -> None:
        """Ignore stale files and clear the previous end marker."""
        path = self.config.observation_path
        if path.exists():
            stat = path.stat()
            self._last_signature = (stat.st_mtime_ns, stat.st_size)

        try:
            self.config.scenario_ended_path.unlink(missing_ok=True)
        except OSError as exc:
            raise RuntimeError(
                "이전 scenario-ended 파일을 제거하지 못했습니다: "
                f"{self.config.scenario_ended_path}"
            ) from exc

    def _ended(self) -> bool:
        path = self.config.scenario_ended_path
        if not path.exists():
            return False
        try:
            text = path.read_text(encoding="utf-8", errors="replace").lower()
            return "true" in text
        except OSError:
            return False

    def read_current(self) -> Observation:
        xml = read_inst_xml(self.config.observation_path)
        return parse_observation_xml(xml, scenario_ended=self._ended())

    def wait_for_new(self, allow_existing_first: bool = True) -> Observation:
        path = self.config.observation_path
        deadline = time.monotonic() + self.config.protocol.observation_timeout_seconds

        while time.monotonic() < deadline:
            if path.exists() and path.stat().st_size > 0:
                stat = path.stat()
                signature = (stat.st_mtime_ns, stat.st_size)

                if (
                    signature != self._last_signature
                    or (allow_existing_first and self._last_signature is None)
                ):
                    try:
                        obs = self.read_current()
                    except (OSError, ValueError):
                        time.sleep(self.config.protocol.poll_interval_seconds)
                        continue
                    self._last_signature = signature
                    return obs

            time.sleep(self.config.protocol.poll_interval_seconds)

        raise TimeoutError(
            f"새 관측 파일을 기다리다 시간 초과: {path}\\n"
            "CMO에서 bootstrap.lua가 실행되었는지, scenario.title이 정확한지 확인하십시오."
        )
